#+TITLE: on-demand-scroll-bar.el - Show scroll bars on demand in Emacs
#+AUTHOR: Florian Rommel
#+LANGUAGE: en

Show scroll bars only when needed.

Enable ~on-demand-scroll-bar-mode~ to show the native graphical
scroll bars when the buffer is not fully visible.

This is experimental and hacky.  Expect breaking changes.


* Installation

Clone the repository and put the path in your load path.
Then, require ~on-demand-scroll-bar~ in your init file:
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "/path/to/~on-demand-scroll-bar")
(require 'on-demand-scroll-bar)
#+END_SRC

Enable ~on-demand-scroll-bar-mode~:
#+BEGIN_SRC emacs-lisp
(on-demand-scroll-bar-mode 1)
#+END_SRC

Emacs's built-in ~scroll-bar-mode~ conflicts with
~on-demand-scroll-bar-mode~ and should be disabled:
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
#+END_SRC

Or use use-package:
#+BEGIN_SRC emacs-lisp
(use-package on-demand-scroll-bar
 :load-path "path/to/on-demand-scroll-bar"
 :config
 (on-demand-scroll-bar-mode 1)
 (scroll-bar-mode -1))
#+END_SRC


Optionally, combine it with custom-css to adapt the scroll-bar appearance.
https://github.com/florommel/custom-css


* Issues

Hidden sections of the buffer (e.g., with org or magit) can result in
"false positives" (the scroll-bar is shown despite the visible part of
the buffer being contained within the window constraints).
Narrowed buffers, however, are handled correctly.
